"""new fields in user model

Revision ID: 970bd4549009
Revises: b4d1e08fb432
Create Date: 2018-04-02 11:21:59.656514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970bd4549009'
down_revision = 'b4d1e08fb432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
